/*
 * jMole.java
 *
 * Created on 25. Juni 2007, 15:06
 */

package org.australia.ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import org.apache.log4j.ConsoleAppender;
import org.apache.log4j.Logger;
import org.apache.log4j.PatternLayout;
import org.australia.algorithm.Criterion;
import org.australia.algorithm.GA;
import org.australia.algorithm.Individual;
import org.australia.algorithm.Status;
import org.australia.config.Config;
import org.australia.problem.Problem;
import org.australia.problem.ProblemBoccia;
import org.australia.problem.ProblemHolmberg;
import org.jdesktop.swingworker.SwingWorker;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.time.RegularTimePeriod;
import org.jfree.data.time.Second;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

/**
 *
 * @author  Daniel_h4x
 */
public class jMole extends javax.swing.JFrame {

    private GAExecutorTask task;
    private Logger logger = Logger.getRootLogger();

    private TimeSeries dynTimeSeries;
    private TimeSeriesCollection dynSeriesCollection;
    private JFreeChart dynChart;
    private RegularTimePeriod dynPeriod;

    /** Creates new form jMole */
    public jMole() {

        logger.addAppender(new ConsoleAppender(new PatternLayout()));
        initComponents();
        drawInitialChart();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TabbedPanel = new javax.swing.JPanel();
        MainTabPane = new javax.swing.JTabbedPane();
        GASettingPanel = new javax.swing.JPanel();
        BasicSettingPanel = new javax.swing.JPanel();
        StartpopLabel = new javax.swing.JLabel();
        GenSizeLabel = new javax.swing.JLabel();
        PopSizeField = new javax.swing.JTextField();
        GenSizeField = new javax.swing.JTextField();
        FeeLabel = new javax.swing.JLabel();
        FeeSpinner = new javax.swing.JSpinner();
        GreedyLabel = new javax.swing.JLabel();
        GreedySpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        PopSizeField1 = new javax.swing.JTextField();
        ChosenProblemField = new javax.swing.JTextField();
        ProblemChooserButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ExtendedSettingPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        LaufzeitInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BestIndiGeneField = new javax.swing.JTextField();
        BestIndiWareHousesField = new javax.swing.JTextField();
        BestIndiFitnessField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        GAProgressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        BestIndiDurationField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BestIndiValidField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BestIndiFeeField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BestIndiProblemField = new javax.swing.JTextField();
        rootChartPanel = new javax.swing.JPanel();
        SetDefaultsButton = new javax.swing.JButton();
        CancelGAButton = new javax.swing.JButton();
        StartGA = new javax.swing.JButton();
        SelPressurePanel2 = new javax.swing.JPanel();
        RandomSelect = new javax.swing.JRadioButton();
        RouletteSelect = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        ParentSelLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ChildrenSpinner = new javax.swing.JSpinner();
        ResultViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        VisualPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TopMenu1 = new javax.swing.JMenuBar();
        DateiMenuItem1 = new javax.swing.JMenu();
        ExportMenu1 = new javax.swing.JMenu();
        CSVMenuItem1 = new javax.swing.JMenuItem();
        ExcelMenuItem1 = new javax.swing.JMenuItem();
        SepVorClose1 = new javax.swing.JSeparator();
        QuitMenuItem1 = new javax.swing.JMenuItem();
        BearbeitenMenu1 = new javax.swing.JMenu();
        UndoMenuItem1 = new javax.swing.JMenuItem();
        RedoMenuItem1 = new javax.swing.JMenuItem();
        SepVorZurueck1 = new javax.swing.JSeparator();
        ZurueckSetzenMenuItem1 = new javax.swing.JMenuItem();
        HilfeMenu1 = new javax.swing.JMenu();
        AboutMenuItem1 = new javax.swing.JMenuItem();
        StatusLabel1 = new javax.swing.JLabel();
        StatusTextLabel = new javax.swing.JLabel();
        TopMenu = new javax.swing.JMenuBar();
        DateiMenuItem = new javax.swing.JMenu();
        ExportMenu = new javax.swing.JMenu();
        CSVMenuItem = new javax.swing.JMenuItem();
        ExcelMenuItem = new javax.swing.JMenuItem();
        SepVorClose = new javax.swing.JSeparator();
        QuitMenuItem = new javax.swing.JMenuItem();
        BearbeitenMenu = new javax.swing.JMenu();
        UndoMenuItem = new javax.swing.JMenuItem();
        RedoMenuItem = new javax.swing.JMenuItem();
        SepVorZurueck = new javax.swing.JSeparator();
        ZurueckSetzenMenuItem = new javax.swing.JMenuItem();
        HilfeMenu = new javax.swing.JMenu();
        AboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jMole");
        setResizable(false);

        BasicSettingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Allgemeine Einstellungen"));

        StartpopLabel.setText("Gr\u00f6\u00dfe der Startpopulation");

        GenSizeLabel.setText("Anzahl der Generationen");

        PopSizeField.setText("100");

        GenSizeField.setText("100");

        FeeLabel.setText("H\u00f6he der Strafkosten");

        FeeSpinner.setModel(new javax.swing.SpinnerNumberModel(10.5d, 0.1d, 100.0d, 0.5d));

        GreedyLabel.setText("Chance auf \"Greedy\"-Start");

        GreedySpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"0% ", "25%", "50%", "75%", "100%"}));

        jLabel8.setText("Durchl\u00e4ufe");
        jLabel8.setEnabled(false);

        PopSizeField1.setText("1");
        PopSizeField1.setEnabled(false);

        ChosenProblemField.setEditable(false);
        ChosenProblemField.setText("Keine Instanz gew\u00e4hlt");

        ProblemChooserButton.setText("Ausw\u00e4hlen");
        ProblemChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProblemChooserButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Probleminstanz");

        org.jdesktop.layout.GroupLayout BasicSettingPanelLayout = new org.jdesktop.layout.GroupLayout(BasicSettingPanel);
        BasicSettingPanel.setLayout(BasicSettingPanelLayout);
        BasicSettingPanelLayout.setHorizontalGroup(
            BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BasicSettingPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(BasicSettingPanelLayout.createSequentialGroup()
                        .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(StartpopLabel)
                            .add(GenSizeLabel))
                        .add(8, 8, 8)
                        .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(GenSizeField)
                            .add(PopSizeField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, BasicSettingPanelLayout.createSequentialGroup()
                        .add(GreedyLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GreedySpinner)))
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(BasicSettingPanelLayout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(FeeLabel))
                    .add(BasicSettingPanelLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel8)))
                .add(17, 17, 17)
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(PopSizeField1)
                    .add(FeeSpinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ChosenProblemField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ProblemChooserButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
        BasicSettingPanelLayout.setVerticalGroup(
            BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BasicSettingPanelLayout.createSequentialGroup()
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(BasicSettingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(StartpopLabel)
                            .add(PopSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel17)
                            .add(ChosenProblemField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(FeeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BasicSettingPanelLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(FeeLabel)
                        .add(9, 9, 9)))
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(GenSizeLabel)
                    .add(GenSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ProblemChooserButton)
                    .add(PopSizeField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BasicSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(GreedyLabel)
                    .add(GreedySpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14))
        );

        ExtendedSettingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kriterium f\u00fcr GA-Abbruch"));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("beenden nach gew\u00e4hlter Anzahl an Generationen");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("beenden nach");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setEnabled(false);
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("beenden nach");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setEnabled(false);
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("beenden nach");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setEnabled(false);
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jTextField1.setText("Min..");
        jTextField1.setEnabled(false);

        jTextField2.setEnabled(false);

        jTextField3.setEnabled(false);

        jLabel7.setText("an Laufzeit");

        jLabel9.setText("Minuten Stagnation");

        jLabel20.setText("Generationen Stagnation");

        org.jdesktop.layout.GroupLayout ExtendedSettingPanelLayout = new org.jdesktop.layout.GroupLayout(ExtendedSettingPanel);
        ExtendedSettingPanel.setLayout(ExtendedSettingPanelLayout);
        ExtendedSettingPanelLayout.setHorizontalGroup(
            ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ExtendedSettingPanelLayout.createSequentialGroup()
                .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ExtendedSettingPanelLayout.createSequentialGroup()
                        .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, ExtendedSettingPanelLayout.createSequentialGroup()
                                .add(jRadioButton4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField3))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, ExtendedSettingPanelLayout.createSequentialGroup()
                                .add(jRadioButton3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField2))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, ExtendedSettingPanelLayout.createSequentialGroup()
                                .add(jRadioButton2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel9)
                            .add(jLabel20))))
                .addContainerGap())
        );
        ExtendedSettingPanelLayout.setVerticalGroup(
            ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ExtendedSettingPanelLayout.createSequentialGroup()
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ExtendedSettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton4)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LaufzeitInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Laufzeit-Informationen"));

        jLabel1.setText("Bestes Individuum");

        jLabel2.setText("Anzahl Lager");

        jLabel3.setText("Fitness");

        BestIndiGeneField.setEditable(false);

        BestIndiWareHousesField.setEditable(false);
        BestIndiWareHousesField.setToolTipText("Anzahl der verwendeten Lager des besten Individuums.");

        BestIndiFitnessField.setEditable(false);
        BestIndiFitnessField.setToolTipText("Fitness des derzeit besten Individuums.");

        jLabel5.setText("Fortschritt");

        GAProgressBar.setToolTipText("Fortschritt des GA...");

        jLabel4.setText("Dauer");

        BestIndiDurationField.setEditable(false);
        BestIndiDurationField.setToolTipText("Fitness des derzeit besten Individuums.");

        jLabel12.setText("Zul\u00e4ssigkeit");

        BestIndiValidField.setEditable(false);
        BestIndiValidField.setToolTipText("Anzahl der verwendeten Lager des besten Individuums.");

        jLabel15.setText("Strafkosten");

        BestIndiFeeField.setEditable(false);
        BestIndiFeeField.setToolTipText("Anzahl der verwendeten Lager des besten Individuums.");

        jLabel16.setText("Probleminstanz");

        BestIndiProblemField.setEditable(false);
        BestIndiProblemField.setToolTipText("Anzahl der verwendeten Lager des besten Individuums.");

        org.jdesktop.layout.GroupLayout LaufzeitInfoPanelLayout = new org.jdesktop.layout.GroupLayout(LaufzeitInfoPanel);
        LaufzeitInfoPanel.setLayout(LaufzeitInfoPanelLayout);
        LaufzeitInfoPanelLayout.setHorizontalGroup(
            LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel2)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, BestIndiFitnessField)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, BestIndiWareHousesField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel12)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, LaufzeitInfoPanelLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel15)
                                                .add(10, 10, 10)))
                                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(BestIndiFeeField)
                                            .add(BestIndiValidField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel16)
                                            .add(jLabel4))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(BestIndiDurationField)
                                            .add(BestIndiProblemField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                                    .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(GAProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 473, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, BestIndiGeneField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 473, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(jLabel5)))
                    .add(rootChartPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 576, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2, Short.MAX_VALUE))
        );
        LaufzeitInfoPanelLayout.setVerticalGroup(
            LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(LaufzeitInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(GAProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(BestIndiGeneField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel12)
                    .add(BestIndiWareHousesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BestIndiProblemField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(BestIndiValidField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(LaufzeitInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel15)
                    .add(BestIndiFitnessField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BestIndiDurationField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(BestIndiFeeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rootChartPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        SetDefaultsButton.setText("Standard wiederherstellen");
        SetDefaultsButton.setEnabled(false);

        CancelGAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/australia/ui/img/stop16.png"))); // NOI18N
        CancelGAButton.setText("GA abbrechen");
        CancelGAButton.setEnabled(false);
        CancelGAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelGAButtonActionPerformed(evt);
            }
        });

        StartGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/australia/ui/img/forward16.png"))); // NOI18N
        StartGA.setText("GA starten");
        StartGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGAActionPerformed(evt);
            }
        });

        SelPressurePanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selektionsdruck"));

        buttonGroup1.add(RandomSelect);
        RandomSelect.setSelected(true);
        RandomSelect.setText("Zufall");
        RandomSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        RandomSelect.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(RouletteSelect);
        RouletteSelect.setText("Roulette");
        RouletteSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        RouletteSelect.setMargin(new java.awt.Insets(0, 0, 0, 0));

        ParentSelLabel2.setText("Auswahl der Eltern:");

        jLabel18.setText("Verh\u00e4ltnis an Kindern");

        jLabel19.setText("zu den Eltern");

        ChildrenSpinner.setModel(new javax.swing.SpinnerNumberModel(2.0d, 1.0d, 5.0d, 1.0d));

        org.jdesktop.layout.GroupLayout SelPressurePanel2Layout = new org.jdesktop.layout.GroupLayout(SelPressurePanel2);
        SelPressurePanel2.setLayout(SelPressurePanel2Layout);
        SelPressurePanel2Layout.setHorizontalGroup(
            SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SelPressurePanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .add(ParentSelLabel2)
                        .add(55, 55, 55)
                        .add(SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(RouletteSelect)
                            .add(RandomSelect)))
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .add(SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(SelPressurePanel2Layout.createSequentialGroup()
                                .add(38, 38, 38)
                                .add(jLabel19))
                            .add(jLabel18))
                        .add(50, 50, 50)
                        .add(ChildrenSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(29, 29, 29))
            .add(jSeparator3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );
        SelPressurePanel2Layout.setVerticalGroup(
            SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SelPressurePanel2Layout.createSequentialGroup()
                .add(SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .add(RouletteSelect)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RandomSelect))
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(ParentSelLabel2)))
                .add(20, 20, 20)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(SelPressurePanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .add(jLabel18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel19))
                    .add(SelPressurePanel2Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(ChildrenSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout GASettingPanelLayout = new org.jdesktop.layout.GroupLayout(GASettingPanel);
        GASettingPanel.setLayout(GASettingPanelLayout);
        GASettingPanelLayout.setHorizontalGroup(
            GASettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(GASettingPanelLayout.createSequentialGroup()
                .add(GASettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(GASettingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(ExtendedSettingPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 321, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SelPressurePanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(GASettingPanelLayout.createSequentialGroup()
                        .add(196, 196, 196)
                        .add(SetDefaultsButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(CancelGAButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(StartGA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(GASettingPanelLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(BasicSettingPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(GASettingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(LaufzeitInfoPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 594, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        GASettingPanelLayout.setVerticalGroup(
            GASettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(GASettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(BasicSettingPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GASettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SelPressurePanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .add(ExtendedSettingPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(LaufzeitInfoPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(GASettingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SetDefaultsButton)
                    .add(CancelGAButton)
                    .add(StartGA))
                .add(5, 5, 5))
        );

        GASettingPanelLayout.linkSize(new java.awt.Component[] {CancelGAButton, SetDefaultsButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

        MainTabPane.addTab("Genetischer Algorithmus", GASettingPanel);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel14.setText("TODO: Anbindung an DB, View konzipiern");

        org.jdesktop.layout.GroupLayout ResultViewPanelLayout = new org.jdesktop.layout.GroupLayout(ResultViewPanel);
        ResultViewPanel.setLayout(ResultViewPanelLayout);
        ResultViewPanelLayout.setHorizontalGroup(
            ResultViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ResultViewPanelLayout.createSequentialGroup()
                .add(ResultViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ResultViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                    .add(ResultViewPanelLayout.createSequentialGroup()
                        .add(168, 168, 168)
                        .add(jLabel14)))
                .addContainerGap())
        );
        ResultViewPanelLayout.setVerticalGroup(
            ResultViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ResultViewPanelLayout.createSequentialGroup()
                .add(48, 48, 48)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(122, 122, 122)
                .add(jLabel14)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        MainTabPane.addTab("Resultat", ResultViewPanel);

        jLabel13.setText("maybe JFreeChart Time-View");

        org.jdesktop.layout.GroupLayout VisualPanelLayout = new org.jdesktop.layout.GroupLayout(VisualPanel);
        VisualPanel.setLayout(VisualPanelLayout);
        VisualPanelLayout.setHorizontalGroup(
            VisualPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisualPanelLayout.createSequentialGroup()
                .add(VisualPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(VisualPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel13))
                    .add(VisualPanelLayout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 512, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        VisualPanelLayout.setVerticalGroup(
            VisualPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel13)
                .add(38, 38, 38)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        MainTabPane.addTab("Visualisierung", VisualPanel);

        org.jdesktop.layout.GroupLayout TabbedPanelLayout = new org.jdesktop.layout.GroupLayout(TabbedPanel);
        TabbedPanel.setLayout(TabbedPanelLayout);
        TabbedPanelLayout.setHorizontalGroup(
            TabbedPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainTabPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 619, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        TabbedPanelLayout.setVerticalGroup(
            TabbedPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainTabPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 722, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        DateiMenuItem1.setMnemonic('D');
        DateiMenuItem1.setText("Datei");

        ExportMenu1.setText("Exportieren");

        CSVMenuItem1.setText("Komma-getrennte Datei");
        ExportMenu1.add(CSVMenuItem1);

        ExcelMenuItem1.setText("Excel Spreadsheet");
        ExportMenu1.add(ExcelMenuItem1);

        DateiMenuItem1.add(ExportMenu1);
        DateiMenuItem1.add(SepVorClose1);

        QuitMenuItem1.setText("jMole beenden");
        QuitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        DateiMenuItem1.add(QuitMenuItem1);

        TopMenu1.add(DateiMenuItem1);

        BearbeitenMenu1.setText("Bearbeiten");

        UndoMenuItem1.setText("R\u00fcckg\u00e4ngig");
        BearbeitenMenu1.add(UndoMenuItem1);

        RedoMenuItem1.setText("Wiederherstellen");
        BearbeitenMenu1.add(RedoMenuItem1);
        BearbeitenMenu1.add(SepVorZurueck1);

        ZurueckSetzenMenuItem1.setText("Einstellungen f\u00fcr GA zur\u00fccksetzen");
        BearbeitenMenu1.add(ZurueckSetzenMenuItem1);

        TopMenu1.add(BearbeitenMenu1);

        HilfeMenu1.setText("Hilfe");

        AboutMenuItem1.setText("\u00dcber jMole");
        AboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        HilfeMenu1.add(AboutMenuItem1);

        TopMenu1.add(HilfeMenu1);

        StatusLabel1.setText("Status:");

        StatusTextLabel.setText("Initialisiert");

        DateiMenuItem.setMnemonic('D');
        DateiMenuItem.setText("Datei");

        ExportMenu.setText("Exportieren");

        CSVMenuItem.setText("Komma-getrennte Datei");
        ExportMenu.add(CSVMenuItem);

        ExcelMenuItem.setText("Excel Spreadsheet");
        ExportMenu.add(ExcelMenuItem);

        DateiMenuItem.add(ExportMenu);
        DateiMenuItem.add(SepVorClose);

        QuitMenuItem.setText("jMole beenden");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        DateiMenuItem.add(QuitMenuItem);

        TopMenu.add(DateiMenuItem);

        BearbeitenMenu.setText("Bearbeiten");

        UndoMenuItem.setText("R\u00fcckg\u00e4ngig");
        BearbeitenMenu.add(UndoMenuItem);

        RedoMenuItem.setText("Wiederherstellen");
        BearbeitenMenu.add(RedoMenuItem);
        BearbeitenMenu.add(SepVorZurueck);

        ZurueckSetzenMenuItem.setText("Einstellungen f\u00fcr GA zur\u00fccksetzen");
        BearbeitenMenu.add(ZurueckSetzenMenuItem);

        TopMenu.add(BearbeitenMenu);

        HilfeMenu.setText("Hilfe");

        AboutMenuItem.setText("\u00dcber jMole");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        HilfeMenu.add(AboutMenuItem);

        TopMenu.add(HilfeMenu);

        setJMenuBar(TopMenu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TabbedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(StatusLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(StatusTextLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(TabbedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(StatusLabel1)
                    .add(StatusTextLabel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean askForExit() {

        int n = JOptionPane.showOptionDialog(this, "Sind Sie sicher, dass Sie jMole beenden wollen?", "Bitte bestätigen!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        return n == JOptionPane.YES_OPTION;
    }
private void CancelGAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelGAButtonActionPerformed

    task.stop();
    StartGA.setEnabled(true);
    CancelGAButton.setEnabled(false);

}//GEN-LAST:event_CancelGAButtonActionPerformed

private void ProblemChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProblemChooserButtonActionPerformed

    new TreeProblemChooser(this, true, ChosenProblemField).setVisible(true);
}//GEN-LAST:event_ProblemChooserButtonActionPerformed

private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed

    if (askForExit()) {
        this.dispose();
        System.exit(0);
    }
}//GEN-LAST:event_QuitMenuItemActionPerformed

    private void StartGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGAActionPerformed

        // if we run the GA for the second time, the TimeSeries for the chart needs to be empty!
        dynTimeSeries.clear();
        
        // ALLGEMEINE EINSTELLUNGEN einlesen
        // get start pop size and amount of generations


        // ALLGEMEINE EINSTELLUNGEN einlesen
        // get start pop size and amount of generations
        int startPopSize = Integer.parseInt(this.PopSizeField.getText());
        int generations = Integer.parseInt(this.GenSizeField.getText());

        // get chosen instance

        // get chosen instance
        String instance = ChosenProblemField.getText();
        //boolean mindStagnation = this.QuitStagnation.isSelected() ? true : false;
        // ERWEITERTE EINSTELLUNGEN einlesen
        // get greedy chance
        //boolean mindStagnation = this.QuitStagnation.isSelected() ? true : false;
        // ERWEITERTE EINSTELLUNGEN einlesen
        // get greedy chance
        SpinnerModel greedyModel = this.GreedySpinner.getModel();
        double greedyChance = this.ConvertGreedyPercentage(greedyModel.getValue());

        // get amount of children to be reproduced

        // get amount of children to be reproduced
        SpinnerNumberModel childrenModel = (SpinnerNumberModel) this.ChildrenSpinner.getModel();
        double forcedChildren = childrenModel.getNumber().doubleValue();

        // get the value for fees

        // get the value for fees
        SpinnerNumberModel feeModel = (SpinnerNumberModel) this.FeeSpinner.getModel();
        double fees = feeModel.getNumber().doubleValue();

        // get selection method

        // get selection method
        boolean rouletteSelected = this.RouletteSelect.isSelected() ? true : false;
        int rouletteSelection = rouletteSelected ? 1 : 0;

        // Test Ouput of Values  DEV ONLY

        // Test Ouput of Values  DEV ONLY
        StringBuilder sb = new StringBuilder();

        sb.append("Input-Values:  ");
        sb.append(" startPopSize " + startPopSize);
        sb.append(" generations " + generations);
        sb.append(" instance " + instance);
        sb.append(" greedyChance " + greedyChance);
        sb.append(" forcedChildren " + forcedChildren);
        sb.append(" fees " + fees);
        sb.append(" rouletteSelection " + rouletteSelection);

        logger.info( sb.toString());

        // Input Werte in Config Klasse schreiben
        Config.setNewGenerationSize(forcedChildren);
        Config.setFee(fees);
        Config.setPercentageGreedy(greedyChance);
        Config.setSelectionMethod(rouletteSelection);

        try {

            Problem problem = null;

            // SwingWorker ab hier!
            if (instance.startsWith("P")) {
                problem = ProblemHolmberg.readProblem(instance);
            } else if (instance.startsWith("i")) {
                problem = ProblemBoccia.readProblem(instance);
            } else if (instance.startsWith("Keine")) {
                StatusTextLabel.setText("Konnte GA nicht starten. Fehler: Keine Probleminstanz gewählt!");
            }

            if (problem != null) {
                task = new GAExecutorTask(problem, startPopSize, generations);


                GAProgressBar.setValue(0);
                BestIndiDurationField.setText("");
                BestIndiFitnessField.setText("");
                BestIndiGeneField.setText("");
                BestIndiWareHousesField.setText("");
                StartGA.setEnabled(false);
                CancelGAButton.setEnabled(true);

                task.execute();
            }
        } catch (Exception e) {

            StatusTextLabel.setText("Konnte GA nicht starten. Fehler:" + e.getClass().getName());
        }
}//GEN-LAST:event_StartGAActionPerformed
    
    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
        new AboutDialog(this, false).setVisible(true);
}//GEN-LAST:event_AboutMenuItemActionPerformed
    
private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            }//GEN-LAST:event_jMenuItem1ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    try {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new java.lang.Runnable() {
            
            public void run() {
                jMole jm = new org.australia.ui.jMole();
                jm.setLocationByPlatform(true);
                jm.setVisible(true);
                
            }
        });
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}


class GAExecutorTask extends SwingWorker<Individual, Status>{
    
    Problem problem;
    GA ga;
    GAStateObserver gaso;
    DurationLabelListener durationListener;
    ChartUpdateListener chartupdater;
    
    Timer timer;
    
    int startPopSize;
    int generations;
    boolean stoppedByUser = false;
    
    public GAExecutorTask(Problem problem, int startPopSize, int generations){
        
        this.problem = problem;
        this.startPopSize = startPopSize;
        this.generations = generations;
                
        durationListener = new DurationLabelListener();
        chartupdater = new ChartUpdateListener(dynTimeSeries,dynPeriod);
                
        gaso = new GAStateObserver(this.generations, chartupdater);
        ga = new GA(problem);
        ga.getStatus().addObserver(gaso);
       
    }
    
    protected Individual doInBackground() {
        
        Individual  bestfound = null;
                
        try {
            StatusTextLabel.setText("GA läuft...");
            
            logger.info("Starting GA as background task");
           
            // start the Timer to throw Actionevents to the chartupdater/DurationListener every 1000 ms
                      
            timer = new Timer(1000, chartupdater);
            
            durationListener.aboutToStart();
            timer.addActionListener(durationListener);
            timer.start();

            
            // Finally start the GA
            bestfound = ga.startAlgorithm(startPopSize, Criterion.GENERATIONS, generations);
                        
            logger.info("Finished GA as background task");
            
        } catch (Exception exception) {
            exception.printStackTrace();
        }

        
        return bestfound;
    }
    
    @Override
    protected void done() {
        
        // remove and stop the timer services -> no more updates to chart/durationlabel     
        timer.removeActionListener(chartupdater);
        timer.removeActionListener(durationListener);
        timer.stop();
        
        if(isCancelled() || stoppedByUser == true){
            StatusTextLabel.setText("GA abgebrochen!");
        } else{
            StatusTextLabel.setText("GA abgeschlossen!");
        }
        StartGA.setEnabled(true);
        CancelGAButton.setEnabled(false);
        
        

   
        
        // print final duration
        // update database (?) / update table on tab 2 (?)
        
        
    }
    
    public void stop(){
        
        try{
            this.ga.setStopped(true);
            stoppedByUser = true;
        }catch(Exception e){
            logger.fatal("Attempt to stop GA failed for reason: \n", e);
            e.printStackTrace();
        }
        
    }
    
}


class GAStateObserver implements Observer{
    
    private ChartUpdateListener cul;
    private int generations;
    
    public GAStateObserver(int generations, ChartUpdateListener cul){
        
        this.generations = generations;
        this.cul = cul;
        
    }
    
    //update UI
    public void update(Observable o, Object arg) {
        
        Status stat = (Status) o;
           
        try{
            java.awt.EventQueue.invokeAndWait( new GAProgressRunnable(stat, generations, cul));
        } catch(Exception e){
            e.printStackTrace();
            
        }
    }
}

class GAProgressRunnable implements Runnable{
    
    
    private Status stat;
    private int generations;
    
    private ChartUpdateListener cul;
    
    public GAProgressRunnable(Status stat, int generations, ChartUpdateListener cul) {
        this.stat = stat;
        this.generations = generations;
        this.cul = cul;
    }
    
    public void run() {

        int iteration = stat.getCurrentGeneration();
        Individual bestIndi = stat.getCurrentBestIndividual();

        // update UI according to these values
        
        //progressbar
        
        int progress = (int)((iteration / (double)generations) * 100);
        GAProgressBar.setValue(progress);
        
        // update the runtime-info field for the best individual
        
        if(bestIndi != null){
            
            String geneString = bestIndi.getGeneString();
            
            if(!geneString.equals(BestIndiGeneField.getText())){
                BestIndiGeneField.setText(geneString);
            }
            
            double fitness = bestIndi.getFitness();
            cul.setFitness(fitness);
                        
            BestIndiFitnessField.setText("" + fitness);
            BestIndiFeeField.setText("" + bestIndi.getFeeCosts());
            
            if(bestIndi.isValid()){
                BestIndiValidField.setText("Zulässig!");
                BestIndiValidField.setForeground(Color.GREEN);
            } else {
                BestIndiValidField.setText("Unzulässig!");
               BestIndiValidField.setForeground(Color.RED);
            }              

            // add all genes to a set to remove duplicates -> amount of warehouse == size of set
            int[] genes = bestIndi.getGene();
            TreeSet<Integer> set = new TreeSet<Integer>();
            
            for (int i = 0; i < genes.length; i++) {
                set.add(genes[i]);
            }
            
            BestIndiWareHousesField.setText("" + set.size());
            
        }        
                
    }   

}

class DurationLabelListener implements ActionListener{

       private Date start = null;
       SimpleDateFormat sdf = new SimpleDateFormat("mm:ss");

        public void aboutToStart() {
            
            if(start == null){
                this.start = new Date();
            }
            
        }
    
        public void actionPerformed(ActionEvent e) {
           
           if(start == null){
               throw new RuntimeException("A Timer-Event was created, but aboutToStart() has not been called.");               
           } 
            
           long ms = new Date().getTime() -  start.getTime();
           BestIndiDurationField.setText(sdf.format(new Date(ms)));

        }
}

/**
 * Updates the chart curve every 1000 ms to the value of its property fitness
 * 
 * 
 * */
class ChartUpdateListener implements ActionListener{

    private double fitness = 0;
    private TimeSeries series = null;
    private RegularTimePeriod period = null;

        public ChartUpdateListener(TimeSeries series, RegularTimePeriod period) {
            
            this.series = series;
            this.period = period;
        } 
    
        public double getFitness() {
            return fitness;
        }

        public void setFitness(double fitness) {
            this.fitness = fitness;
        }
   
        public void actionPerformed(ActionEvent evt) {
            
            period = period.next();  
            series.add(period, fitness);
            
        }
        
}

private void drawInitialChart(){

    logger.info("Trying to draw initial chart");
    
       dynPeriod = new Second();
       dynTimeSeries = new TimeSeries("Verlauf der Fitness", Second.class);
       dynSeriesCollection = new TimeSeriesCollection(dynTimeSeries);
       
       dynChart = ChartFactory.createTimeSeriesChart(
                "",                              // title
                "Zeit",                         // time axis label (x)
                "Fitness",                      // value axis label (y)
                dynSeriesCollection,            // the timeseriescollection
                false,                          // legend
                true,                           // tooltips
                false);                         // urls
        
        XYPlot plot = dynChart.getXYPlot();
        ValueAxis axis = plot.getDomainAxis();
        axis.setAutoRange(true);
        
        // sets the x-axis on a fixed size/range
        //axis.setFixedAutoRange(60000.0);  // 60 seconds
        
        axis = plot.getRangeAxis();
        //axis.setRange(0.0, 100.0);

        
        plot.setBackgroundPaint(Color.lightGray);
        plot.setDomainGridlinePaint(Color.white);
        plot.setRangeGridlinePaint(Color.white);
        
        //draw a line on y-axis across the graph
        //draw the line only on actual data points
        plot.setRangeCrosshairVisible(true);
        plot.setRangeCrosshairLockedOnData(true);
        
                
        XYLineAndShapeRenderer r = (XYLineAndShapeRenderer) plot.getRenderer();
        r.setUseFillPaint(true);
        r.setBaseFillPaint(Color.white);

        int w = rootChartPanel.getWidth();
        int h = rootChartPanel.getHeight();
        
        ChartPanel chartPanel = new ChartPanel(dynChart,w,h,w,h,w,h,true,false,false,false,true,true);
        
        rootChartPanel.add(chartPanel);
        
        logger.info("Added initial chart to UI");
 
}

/**
 * BAAAAAD practice.....
 *
 * it feels so wrong... at least it works
 *
 */
private double ConvertGreedyPercentage(Object spinnerValue){
    
    String inputPercentage = (String)spinnerValue;
    double actualPercentage = -1;
    
    if(inputPercentage.startsWith("0")){
        actualPercentage = 0.0;
    } else if(inputPercentage.startsWith("25")){
        actualPercentage = 0.25;
    } else if(inputPercentage.startsWith("50")){
        actualPercentage = 0.5;
    } else if(inputPercentage.startsWith("75")){
        actualPercentage = 0.75;
    } else if(inputPercentage.startsWith("100"))
        actualPercentage = 1.0;
    
    return actualPercentage;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem AboutMenuItem1;
    private javax.swing.JPanel BasicSettingPanel;
    private javax.swing.JMenu BearbeitenMenu;
    private javax.swing.JMenu BearbeitenMenu1;
    private javax.swing.JTextField BestIndiDurationField;
    private javax.swing.JTextField BestIndiFeeField;
    private javax.swing.JTextField BestIndiFitnessField;
    private javax.swing.JTextField BestIndiGeneField;
    private javax.swing.JTextField BestIndiProblemField;
    private javax.swing.JTextField BestIndiValidField;
    private javax.swing.JTextField BestIndiWareHousesField;
    private javax.swing.JMenuItem CSVMenuItem;
    private javax.swing.JMenuItem CSVMenuItem1;
    private javax.swing.JButton CancelGAButton;
    private javax.swing.JSpinner ChildrenSpinner;
    private javax.swing.JTextField ChosenProblemField;
    private javax.swing.JMenu DateiMenuItem;
    private javax.swing.JMenu DateiMenuItem1;
    private javax.swing.JMenuItem ExcelMenuItem;
    private javax.swing.JMenuItem ExcelMenuItem1;
    private javax.swing.JMenu ExportMenu;
    private javax.swing.JMenu ExportMenu1;
    private javax.swing.JPanel ExtendedSettingPanel;
    private javax.swing.JLabel FeeLabel;
    private javax.swing.JSpinner FeeSpinner;
    private javax.swing.JProgressBar GAProgressBar;
    private javax.swing.JPanel GASettingPanel;
    private javax.swing.JTextField GenSizeField;
    private javax.swing.JLabel GenSizeLabel;
    private javax.swing.JLabel GreedyLabel;
    private javax.swing.JSpinner GreedySpinner;
    private javax.swing.JMenu HilfeMenu;
    private javax.swing.JMenu HilfeMenu1;
    private javax.swing.JPanel LaufzeitInfoPanel;
    private javax.swing.JTabbedPane MainTabPane;
    private javax.swing.JLabel ParentSelLabel2;
    private javax.swing.JTextField PopSizeField;
    private javax.swing.JTextField PopSizeField1;
    private javax.swing.JButton ProblemChooserButton;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JMenuItem QuitMenuItem1;
    private javax.swing.JRadioButton RandomSelect;
    private javax.swing.JMenuItem RedoMenuItem;
    private javax.swing.JMenuItem RedoMenuItem1;
    private javax.swing.JPanel ResultViewPanel;
    private javax.swing.JRadioButton RouletteSelect;
    private javax.swing.JPanel SelPressurePanel2;
    private javax.swing.JSeparator SepVorClose;
    private javax.swing.JSeparator SepVorClose1;
    private javax.swing.JSeparator SepVorZurueck;
    private javax.swing.JSeparator SepVorZurueck1;
    private javax.swing.JButton SetDefaultsButton;
    private javax.swing.JButton StartGA;
    private javax.swing.JLabel StartpopLabel;
    private javax.swing.JLabel StatusLabel1;
    private javax.swing.JLabel StatusTextLabel;
    private javax.swing.JPanel TabbedPanel;
    private javax.swing.JMenuBar TopMenu;
    private javax.swing.JMenuBar TopMenu1;
    private javax.swing.JMenuItem UndoMenuItem;
    private javax.swing.JMenuItem UndoMenuItem1;
    private javax.swing.JPanel VisualPanel;
    private javax.swing.JMenuItem ZurueckSetzenMenuItem;
    private javax.swing.JMenuItem ZurueckSetzenMenuItem1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel rootChartPanel;
    // End of variables declaration//GEN-END:variables
    
}
